name: Sync Info
on:

  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - README.md
      - DESC.txt
  pull_request:
    branches:
      - main
    paths:
      - README.md
      - DESC.txt

jobs:
  sync_description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Read Desc
        id: desc
        run: echo "value=$(cat DESC.txt)" >> $GITHUB_OUTPUT

      - name: Update GitHub repository description
        run: gh repo edit --description "${{ steps.desc.outputs.value }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: "${{ secrets.DOCKER_USERNAME }}/external-service-healthcheck"
          short-description: ${{ steps.desc.outputs.value }}
          readme-filepath: ./README.md
